version: "3"

services:
  data-subscriber:
    build:
      context: .
      dockerfile: stream.Dockerfile
    container_name: data-subscriber

networks:
  default:
    name: mlops-network
    external: true