version: "3"

services:
  api-with-model:
    build:
      context: .
      dockerfile: FastAPI.Dockerfile
    container_name: api-with-model
    ports:
      - 8000:8000
    healthcheck:
      test:
        - curl -X POST http://localhost:8000/predict
        - -H
        - "Content-Type: application/json"
        - -d
        - '{"feature_a": 12.77, "feature_b": 29.43, "feature_c": 81.35, "feature_d": 507.9, "feature_e": 0.08276, "feature_f": 0.04234, "feature_g": 0.01997, "feature_h": 0.01499, "feature_i": 0.1539, "feature_j": 0.05637, "feature_k": 0.2409, "feature_l": 1.367, "feature_m": 1.477, "feature_n": 18.76, "feature_o": 0.008835, "feature_p": 0.01233, "feature_q": 0.01328, "feature_r": 0.009305, "feature_s": 0.01897, "feature_t": 0.001726, "feature_u": 13.87, "feature_v": 36.0, "feature_w": 88.1, "feature_x": 594.7, "feature_y": 0.1234, "feature_z": 0.1064, "feature_aa": 0.08653, "feature_bb": 0.06498, "feature_cc": 0.2407, "feature_dd": 0.06484}'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: mlops-network
    external: true